version: '3.8'

services:
  gateway:
    build:
      context: ./gateway-service
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - microservico1
      - microservico2

  microservico1:
    build:
      context: ./microservico1
    container_name: microservico1
    ports:
      - "8081:8081"

  microservico2:
    build:
      context: ./microservico2
    container_name: microservico2
    ports:
      - "8082:8082"
