server:
  port: 8080

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: microservico1
          uri: http://microservico1:8081
          predicates:
            - Path=/microservico1/**
          filters:
            - StripPrefix=1

        - id: microservico2
          uri: http://microservico2:8082
          predicates:
            - Path=/microservico2/**
          filters:
            - StripPrefix=1
